### ISSUE TITLE
Incompatible Characters by default

### ISSUE THREAD

**Issue by saivan** [daniel3735928559/guppy#138]
I verified that this is also the case on the website, but guppy seems to be having a font issue with katex. So I'm getting all of this output in the console. Any idea what could be causing this?

![image](https://user-images.githubusercontent.com/8543370/54592133-d5d02200-4a7f-11e9-8bc3-4f38cc63e18e.png)

**Comment by saivan** [comment]
Tracing this back; it seems to be the emoji on the on-screen keyboard.
They don't seem to be natively supported by the katex font. 

![image](https://user-images.githubusercontent.com/8543370/54649365-0060c000-4afe-11e9-98b8-4d3c847cf53d.png)

Some display, but the last one does not.

**Comment by saivan** [comment]
I was able to fix this by providing my own symbols file that didn't include these symbols. I think these symbols should probably be removed by default, since they aren't supported on every system.

**Comment by iamprayush** [comment]
I'm also facing this issue (see [this thread](https://github.com/oppia/oppia/pull/9400#discussion_r438941996) for more context) and I'm able to resolve it by removing these symbols from guppy.js. As @saivan mentioned, we could remove these symbols by default since they are not natively supported by KaTeX.
@daniel3735928559 I've created a [PR](https://github.com/daniel3735928559/guppy/pull/173) with these changes. Please let me know if there's a better fix for this, thanks!
