### ISSUE TITLE
Be able to parse multi-character subscripts

### ISSUE THREAD

**Issue by AlienKevin** [daniel3735928559/guppy#164]
Currently, guppy doesn't accept variable names such as "m_earth" and "v_11" which may be useful many times. Can guppy give an option to allow more descriptive multi-character subscripts?

**Comment by akrinke** [comment]
In our [MathML editor](http://mpfo.org/mpfo-0.7/_static/mathml-editor/index.html) we add variables like this as symbols to Guppy using `Guppy("guppy1").engine.add_symbol()`. Maybe you can automatically detect and add such variable names during input.

**Comment by EmaGht** [comment]
@akrinke Not really...
![image](https://user-images.githubusercontent.com/12494403/74165254-25ce4f00-4c25-11ea-8a51-14e00cc12165.png)

The "_" character will always be read as a subscript and printed as "characters after this are lowercase". 

@AlienKevin The only real thing you can do is to not use underscores.
Unfortunately there are no other free math editors (that i could find) that allows Guppy's flexibility, but Guppy is a bug-land (That's honestly to be expected since is in BETA stage) so you will eventually have to fix the source code and adapt it to your needs. Good thing is, unless you are debugging the parse-tokenize section it is pretty straightforward

Really wish this project wasn't left to itself T_T

**Comment by akrinke** [comment]
Your example of a multi-digit index already works with standard guppy:
![grafik](https://user-images.githubusercontent.com/369377/74168264-c0309180-4c29-11ea-959f-d7638d09acad.png)

But words as index do not work:
![grafik](https://user-images.githubusercontent.com/369377/74168355-e5bd9b00-4c29-11ea-8621-32e2f1199deb.png)

If you add these variable names as symbols, it works:
![grafik](https://user-images.githubusercontent.com/369377/74168577-40ef8d80-4c2a-11ea-891b-3dc650a993b4.png)

However, you are right that the underscore is not used in this case.

**Comment by AlienKevin** [comment]
Thank you, guys! Your solutions work for me.
