### ISSUE TITLE
Show cursor when the div is activated

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#20]
Would it be possible to show a red cursor (or some kind of "you can type here" indication) when the guppy div is activated? At the moment it's unclear that the div has been focused on.

**Comment by daniel3735928559** [comment]
Can you link me to an example?  Right now the demo page http://daniel3735928559.github.io/guppy/ has the div as greyed out when inactive and turns white with a slightly shiny blue border when active, and there should be [?] showing up in red in the div when no input has been supplied.  Is not all of this, or perhaps none of this, the case?

**Comment by seanlip** [comment]
/cc @wxyxinyu

The grey and white work correctly, though occasionally the [?] doesn't show (though in my last three attempts it did show, so perhaps it was just a transient thing).

However, grey is usually used to indicate that a textarea is disabled, and a blinking vertical cursor is used to indicate whether it's focused or not, much like this GitHub one I'm typing in. I know how guppy works, so I'm kinda immune to this, but @wxyxinyu pointed out at review time that she was confused about whether she could type input into the box because of the lack of a flashing cursor.

**Comment by daniel3735928559** [comment]
I see.  That's a good point about the way normal text fields work.  It's not entirely obvious what blinking the cursor should be in this case, since it is the [?] instead of the usual caret.  Maybe I'll have to rethink the cursor/blank box interface a little bit.  In the meanwhile, I can, for example, make the border turn a more obvious blue and try to track down the "sometimes the [?] doesn't show" issue (as that seems problematic anyway).  

Do you have an opinion about the grey background for inactive?  The textarea I'm typing this reply into, for instance, does this too.

**Comment by seanlip** [comment]
Oh, sorry, you're absolutely right about the grey background for inactive. I think that can remain, but perhaps be a bit subtler, like this textarea (the existing guppy textarea is a bit too grey at the moment).

**Comment by daniel3735928559** [comment]
Less greyness implemented, and as I understand it the other issues here are more or less resolved, so I'll close this.  Feel free to reopen if there are still problems.
