### ISSUE TITLE
Help Required?

### ISSUE THREAD

**Issue by saivan** [daniel3735928559/guppy#23]
Hello daniel,

I was wondering if you needed any help maintaining this project, 
It looks like it has a tonne of potential, and I'd love to help out and get it kicking again :)

**Comment by daniel3735928559** [comment]
Glad it seems useful!  I am mostly buried in a couple of school projects and since the editor does mostly what I need already, it will likely wait until after these settle down somewhat (4-6 weeks or so).  

Longer term, I am highly interested in bringing this editor to a state of general usability.  While I don't have a clear picture of everything that entails, the current set of items to move in that direction are expressed in issues tagged as "blocking 1.0" (some of which require an understanding of KaTeX's source code in addition).  Of these, the hardest but most important is almost certainly #10.  

If you are interested in contributing, I will very happily review pull requests!  Did you have a specific use-case or modification in mind?  I could try to spin up a "developer's guide" describing the organisation of the source code, say.
