### ISSUE TITLE
Is there a matrix support?

### ISSUE THREAD

**Issue by PeterBocan** [daniel3735928559/guppy#31]
Is there a matrix support?

**Comment by daniel3735928559** [comment]
Kind of.  You can get matrices of a specific, fixed dimension by adding an entry to `src/symbols.json` such as: 

```
    "mat2":
    {
      "output":{
        "latex":"\\left(\\begin{matrix}{$1} & {$2} \\\\{$3} & {$4}\\end{matrix}\\right)",
        "text":"[[{$1},{$2}],[{$3},{$4}]]"
      },
      "current":0,
      "type":"matrix",
      "attrs":{
        "up":[1,1,2,2],
        "down":[3,3,4,4],
        "name":["top_left","top_right","bottom_left","bottom_right"]
      }
    }
```

which would let you write a 2x2 matrix by typing `mat2` into the editor (although this didn't work before because of an escaping issue with the ampersands, which I have now fixed).  

A mechanism for writing general matrices, vectors, lists, etc. that can be resized is on my wish-list but does not currently exist.

**Comment by kalbhairab** [comment]
Sir i don't know more of latex, js and .json file but i have seen this to make big matrix. I have written logic in python but you may make it in .js file. I didn't know how to give indentation here in markdown

def matrix(row,col):
    print r"\begin{bmatrix}"
    for i in range(row):
        print "? &"*(col-1) + r" ? \\"
    print r"\begin{bmatrix}"
    
print matrix(3,4)

**output
\begin{bmatrix}
? &? &? & ? \\
? &? &? & ? \\
? &? &? & ? \\
\begin{bmatrix}
None**

**Comment by daniel3735928559** [comment]
#42 outlines the plan to add matrix and vector support more generally than just adding all n-by-m matrices separately to the JSON.  I'll close this issue as being a subset of that one, but feel free to comment on #42 if the planned matrix implementation doesn't quite do what you need.
