### ISSUE TITLE
please make settings as smath

### ISSUE THREAD

**Issue by kalbhairab** [daniel3735928559/guppy#33]
Dear sir,
If you can make settings then please make settigs like smath or mathcad which is very simple to write math. (http://en.smath.info/)

**Comment by daniel3735928559** [comment]
Hello!  What kinds of settings specifically were you thinking of?  (Maybe post a screenshot if possible?)  I tried looking at the cloud version of smath but didn't see anything but "Properties", which just had the name of the sheet.  

(Also, unrelatedly, I saw the [issue](https://github.com/Khan/KaTeX/issues/569) you made for KaTeX about nth root, so just in case you haven't solved it already: if you add an entry like the following: 

```
    "root":
    {"output":{
        "latex":"\\sqrt[{$1}]{{$2}}",
	"text":"root({$1},{$2})"},
     "current":0,
     "type":"root",
     "attrs":{
	 "up":[1,1],
	 "down":[2,2],
	 "name":["index","radicand"]}
    },
```

to the dictionary in `src/symbols.json`, you should then be able to type "root" and have an nth root appear.)

**Comment by kalbhairab** [comment]
Thanks for your advice.
I have become a fan of yours project. Imagine how useful it would be, if we can incorporate it  in jupyter notebook for typing math expressions easily and if we can link sympy of python to evaluate the math expression inline as in **smath studio or mathcad** to get nice symbolic output by linking code converted from your wysiwyg editor and vice-versa then the calculations in python would go to new level without worrying to know about latex, sympy, etc for use.


But i would like you to suggest you for wysiwyg editor. I have said settings relating to typing expressions in wysiwyg editor in smath. Hope you consider my suggestion. 
1. Please add the code provided by you in your source for **root** so that we can work it online
2.The settings would be better if you add **tab** or similar for completion for symbols like diff, int, matrix, etc so that if we want to make custom name with beginning with these keywords then it would be easy. 
for example **cost** can't be typed in your wysiwyg editor. Also if in future your keys are more then it is easy to maintain.
3. Also we can't write sin^2(x) or other related in you wysiwyg. It is better if we type **sin->tab->^->(** then it would render as we desire. Please try to see how math typing is working in **smath**(http://smath.info/wiki/GetFile.aspx?File=Tutorials/SMathPrimer.pdf) so that this editor will get new level of features in future.
4. Also if we can write custom characters like underscore, caret, etc. then it would be more useful.

**Comment by daniel3735928559** [comment]
I can see Jupyter being a cool use-case!  Probably the first thing would be to have sympy versions of all the outputs in `symbols.json` in addition to the LaTeX and plain text outputs already there.  The second thing would be to be able to import content from sympy's evaluation back into the editor.  It looks like sympy can ouput content MathML, so that would probably be the easiest thing to convert to guppy's internal format.  

To your suggestions: 

1. The root change is pushed now.  This is a reasonably general-purpose symbol so I have added it, but in general, I think a reasonable policy would involve everyone having potentially separate symbol definitions and simply distributing their symbol file along with their application (much as different LaTeX users would have a personal `.sty` file nowadays).  I could be persuaded otherwise on this, however.  

2. Yeah, this is more or less #15.  However, for educational applications I do like that `sin` and `cos` automatically create the function objects, since that will likely be more intuitive for students to type than `sin <tab>`.  However for advanced users with more symbols (such as maybe `cost`), it might be worth making this a configuration option.  I will look into this.    

3. This one is slightly difficult: The editor design is that the only things you can enter are basic arithmetic operations (`x + 2y`, say) and functions defined in the symbols file.  That way, your input is always guaranteed to have meaning (no writing `sin + cos`, say).  So since the normal way of entering sin^2 requires that `sin` be separated somewhat from its argument, this gets slightly difficult.  In general, my goal is not to make this editor into a full symbolic calculator as smath seems to be, but only to make it possible for someone else who is writing such a calculator to get input more easily via this editor.

4. It is possible I don't understand this one, so an example of what you want to do would be helpful.  A general comment though: One goal of the editor is to be able to distinguish, for example, whether `dy/dx` refers to "d times y divided by d times x" or "the derivative of y wrt x".  So the only straight characters that are supported are basic arithmetic operations, and everything else is a symbol, and if you want to enter anything beyond just +, -, *, / then you are supposed to define a symbol for that thing.

**Comment by daniel3735928559** [comment]
Now that there is an option to disable auto-replace of symbols, I've added the suggestion where tab will trigger the replacement.  So now, `sin<tab>` will insert the sine function.  See #54 and/or [doc/api.md](https://github.com/daniel3735928559/guppy/blob/master/doc/api.md) for how to disable autoreplacement.
