### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#35]
On Chrome, we have been seeing some issues with using guppy: the textarea appears, but clicking to it shows the red "[?]" and typing further does not do anything. This is not always reproducible but happens with non-negligible frequency. After a while, I managed to reproduce this locally with v1.0.0 as shown in the screenshot below.

The problematic line in question is actually line 268 of guppy.js (I added some console log statements in the screenshot below). It arises in the get_loc() function, when guppy is trying to find a bounding client rect. I logged the values of `g`, `g.editor`, and `bb`, and in the Chrome dev tools I found that when I expand the first `g.editor` there's nothing inside the katex span. I'm not sure if that span is being picked up from the subsequent console logs, though (since get_loc() keeps getting called and all the logged stuff looks correct in the subsequent calls).

Please let me know if you need more info (though note that this bug only happens sometimes, and is quite hard to reproduce reliably). Also, would it be possible to make this somehow fail-safe, so that a bad call to get_loc() doesn't crash the whole thing?

![guppy-error](https://cloud.githubusercontent.com/assets/10575562/20699495/7aa93272-b5bc-11e6-988b-9611b422f0ec.png)

**Comment by daniel3735928559** [comment]
I think I have occasionally observed this as well, but it didn't seem to affect functionality so I ignored it.  I am not sure if I have seen it lately, and I would be curious if you observe it on, say, 20aeed8645e01929802af7b7e9f412a7a611b3fc.  I was unable to reproduce it on any commit, even jacking up simulated network latency, say.  

Nevertheless, I have made `get_loc` fail silently now, since (hopefully) more error-checking can't hurt.  So in theory this error should no longer appear on the latest commit.  Let me know if it seems fixed there.

**Comment by seanlip** [comment]
Thanks a lot, @daniel3735928559! I think one of the things I tried to do in order to repro it was to clear my cache, since it failed the first time but didn't fail any of the subsequent times I reloaded the page. So I figured it might possibly be due to some async thing taking a while to load (maybe the katex lib or similar).

I think your changes should fix it, so thanks very much for doing that! I will let you know if I get reports of this happening again, or am able to reproduce it.
