### ISSUE TITLE
Selecting editor doesn't trigger keyboard in mobile

### ISSUE THREAD

**Issue by jiggzson** [daniel3735928559/guppy#49]
When selecting the editor in mobile devices, the keyboard doesn't get opened. I tried it on different browsers in Linux and Windows. I also tried it on Safari for iOS. It doesn't seem to trigger on any of those.

Thanks.

**Comment by daniel3735928559** [comment]
This is a hard one that I've wanted to solve for a while now, but have had very little success with to date.  I'll keep an eye out, and anyone with an idea is welcomed to chime in, but all the bodges (invisible text fields being focused in onclick handlers) that I've seen suggested have not worked for me.

**Comment by jiggzson** [comment]
Have you by any chance tried using a text field with height, width, padding, margin, and border to 0 and using its text as a relay to guppy. I haven't had a chance to look dig in deep into guppy's inner workings yet so I'm just throwing it out there.

**Comment by Oishikatta** [comment]
I also need to use Guppy on mobile devices.

Does anyone have any input, suggestions, etc on the implementation here: https://oishikatta.github.io/guppy/

- If on mobile, overlay the Guppy div with an invisible button element.
- In that button's onclick handler, activate the Guppy instance and then focus a text input field (0 h/w/padding/margin/border). This brings up the mobile keyboard due to being called from an onclick event.
- When the text input field is updated, empty the Guppy instance and replay the series of keys matching the contents of the text input field to refill it. Debounce to 1 empty/refill per 100ms.


Code: https://github.com/Oishikatta/guppy/blob/gh-pages/index.js#L25-L111

One obvious issue is no text selection (deletion only by backspace).

It seems to work decently on Android 7.x (Chrome, Firefox). I'm not able to test on Apple devices.

Thanks.

**Comment by daniel3735928559** [comment]
I got to try it briefly on a friend's iPhone.  It works better than anything I've tried to date, but is somewhat inconsistent: sometimes tapping the editor wouldn't bring up the keyboard.  It always did bring up the keyboard the first time, however, and I'm not entirely sure what are the precise set of conditions under which it works.

One thing I noticed is that the keyboard doesn't seem to make mathematical symbols so readily accessible, and there isn't really a notion of shift+arrows for selecting.  I will see what I can do about touch selection, but what might be necessary in the end is a fake on-screen keyboard or otherwise for a touch-based editing interface.

**Comment by daniel3735928559** [comment]
Finally got around to this.  I decided to make a custom maths keyboard with the symbols included.  Can be tested at https://daniel3735928559.github.io/guppy/examples/osk.html

**Comment by jiggzson** [comment]
Wow. This is awesome! I can finally switch back to Guppy as my primary editor. It would be nice if it had a QWERTY layout. I forked Guppy and made some modifications to the 'abc' group in guppy_osk.js file. It's really rough but basically serves as a prototype. This should probably be its own tab if you're OK with this. Maybe something like QWERTY and qwerty. If you get  a chance please take a look and let me know. I know you mention that you're busy so no rush.

Thanks.

**Comment by daniel3735928559** [comment]
Ah, yeah, that's a good idea and I'd be happy to just replace ABC with
Qwerty (with apologies to the Dvorak crowd).  Your implementation looks
like a good first crack in that direction, though I'll probably have to
mess with the zxcvbnm row a bit when the time comes.

**Comment by daniel3735928559** [comment]
OK--I played with it a bit and I think it is at least getting closer to reasonable.  [Check it out](https://daniel3735928559.github.io/guppy/examples/osk.html) and if you have further ideas, I remain interested.

**Comment by jiggzson** [comment]
This is perfect! I'll go ahead and update my project as soon as I get some time. One minor issue is that there's no easy way to find out which buttons corresponds to which function. Hovering over the button doesn't seem to help either. I guess I can browse through the source code and figure this out.

Thanks!
