### ISSUE TITLE
Create mechanism for importing text 

### ISSUE THREAD

**Issue by briskweb** [daniel3735928559/guppy#65]
It would be really nice if there were a mechanism for importing text.
That way, another mechanism could be implemented that allows the user to switch between the WYSIWYG editor and a text field.

**Comment by daniel3735928559** [comment]
Agreed.  This is quite a bit of work, however, since it requires a full parser, and making some decisions about how to interpret input (e.g. dy/dx should be understood as derivative(y,x) and not as "((d*y)/d)*x" or similar.  

My suspicion is that the right thing to do will be to take some existing parsing code and repurpose it for this.

**Comment by briskweb** [comment]
I actually wouldn't mind too much about this problem with the derivative. At least not in the first step.
My expectation would just be that Guppy is able to import a text written in the same format as used for export.

**Comment by daniel3735928559** [comment]
[math-expressions](https://github.com/kisonecat/math-expressions) has taken care of this for us; see [new example](https://daniel3735928559.github.io/guppy/examples/import.html)
