### ISSUE TITLE
xml function to PHP code parser

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#66]
HI Daniel,

my next task for my project is to develop a XML to PHP function parser which will allow the xml function markup string to be converted to PHP code to allow for real calculations to be done.

For the initial phase I am going to restrict to simple calculation, (+/-/x//, sum over an index, average over an index, power functions, sqrt, sin/cos/tan etc, mod).   

Question: are you aware of any existing such parsers possibly for other coding languages?

**Comment by daniel3735928559** [comment]
I guess there are three types of approach: 

* Have the editor send the XML to the server and have the server evaluate it.

* Have the client turn the XML into PHP and run it on the server.

* Have the client evaluate the XML directly and send the result to the server.  

The first option might be accomplished by sending the text representation of the expression and using something like [this](https://www.phpclasses.org/package/2695-PHP-Safely-evaluate-mathematical-expressions.html) on the server side.

The second option is probably pretty easy by adding a "php" entry to each symbol's output, but very bad for security.

The third option could might be the easiest because of libraries like [this one](https://github.com/arthanzel/evaluatex).

**Comment by aurovrata** [comment]
thanks for the suggestion, I think the first option looks promising for what I have in mind.
