### ISSUE TITLE
space cant be given

### ISSUE THREAD

**Issue by abhinov2** [daniel3735928559/guppy#69]
could u urgently look into the problem of not being able to give space between letters.
i tried using phantom character/ other latex symbols of spacebar but though i am able to create space the problem is the div in which everythng is being displayed is becoming inactive. if i click it again then am able to write further

**Comment by daniel3735928559** [comment]
This week I am supposed to be attending to something else, so I shouldn't spend much time on this until Friday.  I also don't quite entirely understand what you're trying to do: Are you trying to have a space between math symbols, or, as your earlier comment seems to suggest, do you just want space when in text mode?  

Space in math mode isn't really supported and I'm not sure if it makes sense to support.  Space in text mode, because it was a two-line change, I've fixed just now and it should now work.  

If that's not what you needed, could you give a report containing: 

* The steps you perform in the editor
* What you want to see when you do those steps
* What you actually see when you do those steps

See, for example, #39.

**Comment by abhinov2** [comment]
thanks a lot. it works in text mode. but to go back to math mode do we have to click outside .. or is there shortcut to initiate math mode
suggestion : u cud incorporate touch-start in osk html , so that it would work in IOS.

**Comment by daniel3735928559** [comment]
I think this issue is settled.  I'll close it and address the other things you bring up in the corresponding issues you've opened.  Thanks again.
