### ISSUE TITLE
how to get back to math mode once you get into text mode

### ISSUE THREAD

**Issue by abhinov2** [daniel3735928559/guppy#70]
Thanks a lot. it works in text mode. but to go back to math mode do we have to click outside .. or is there any shortcut to initiate math mode
suggestion : u cud incorporate touch-start in osk html , so that it would work in IOS.

**Comment by daniel3735928559** [comment]
If you're at the end of a text element, you can just hit the right arrow key and you'll be out of it.  Think of it as a text "box", rather than text "mode".  It might make sense to change the appearance a little bit so that this is more obvious.  I shall think about it.  

Also, when I get back to this I'll explore the touchstart business.  Thanks for the help!

**Comment by daniel3735928559** [comment]
OK--I've added a grey border around active textboxes to hopefully make it a little more obvious what to do.
