### ISSUE TITLE
Functions are treated as distributive multiplication

### ISSUE THREAD

**Issue by blueridanus** [daniel3735928559/guppy#77]
An expression such as `f(x)` is handled as the multiplication of two variables, `f*(x)`.

LaTeX output:
`f\left(x\right)`
Text output:
`f *  ( x )  ` (why the double spaces?)
JSON output:
`["*",[["var",["f"]],["bracket",[["var",["x"]]],{}]]]`
XML output:
```xml
<m><e>f</e><f type="bracket" group="functions"><b p="latex">\left(<r ref="1"/>\right)</b><b p="text">(<r ref="1"/>)</b><c delete="1" is_bracket="yes"><e>x</e></c></f><e></e></m>
```

**Comment by daniel3735928559** [comment]
This is intended behaviour: Guppy is meant to track what the input means as well as what it looks like.  Both function evaluation "f(x)" and multiplication "f(x)" look the same, so how to tell which is meant?  In principle, there are heuristics that could cover some of these cases, but the convention chosen here is that if `f(x)` is entered, this means f*(x) unless f is explicitly defined as a symbol for the editor (done with an entry in a symbols JSON file (e.g. sym/symbols.json); symbols can also be added programmatically on the fly.)

Thus if you have a situation where, say, f, g, and h are actual functions, you would tell the editor that information (the interface for doing so is being reworked this sprint, in fact, otherwise I'd give the code here) and then it would treat them accordingly.

**Comment by daniel3735928559** [comment]
The interface is now more settled: If you want to, for example, use f, g, and h as function for an editor, there are three ways: 

The preferred method would be to add them to your symbols.json with a line like: 
 
```
"my_functions":{"template":"func", "values":["f","g","h"]},
```

If you want to add them to the editor dynamically, then you can add them to all instances of the editor with: 

```
Guppy.add_global_symbol("f",{},"func")
Guppy.add_global_symbol("g",{},"func")
Guppy.add_global_symbol("h,{},"func")
```

Or you can add them to a specific instance of the editor (in this example, `guppy12`) like: 

```
guppy12.backend.add_symbol("f",{},"func")
guppy12.backend.add_symbol("g",{},"func")
guppy12.backend.add_symbol("h,{},"func")
```
