### ISSUE TITLE
Missing GuppyOSK demo and documentation

### ISSUE THREAD

**Issue by jiggzson** [daniel3735928559/guppy#80]
This link [https://github.com/daniel3735928559/guppy/blob/master/doc/other_api.md#guppyosk](https://github.com/daniel3735928559/guppy/blob/master/doc/other_api.md#guppyosk) is mentioned several times through out the documentation including the repository readme but is missing. Has the location changed?

**Comment by daniel3735928559** [comment]
The GuppyOSK documentation is now [here](http://daniel3735928559.github.io/guppy/site/docs/guppymath/2.0.0-alpha/GuppyOSK.html) and the example is [here](http://daniel3735928559.github.io/guppy/site/examples/osk/).  

Those locations might change once more in the near future since I'm in the middle of editing the documentation, but once that's stable I'll update the README and the references accordingly (this issue will serve as a reminder).  Thanks for pointing it out!

**Comment by jiggzson** [comment]
Got it. Thanks! I saw the new documentation location but I couldn't find demo location.
