### ISSUE TITLE
Prevent guppy from auto-inserting certain functions

### ISSUE THREAD

**Issue by jiggzson** [daniel3735928559/guppy#82]
I have this function name "expand".  Whenever I try to insert expand, guppy assumes I'm attempting to insert 'exp' and auto-inserts that function for me. At first I thought that blacklisting "exp" would be my solution but it turns out that it only disallows its usage from being exported to text or LaTeX. Is there presently any way to achieve this?

**Comment by daniel3735928559** [comment]
This kind of thing has been a recurring issue.  There are things a user can do when it comes up, as described in #79, but that requires the user learning about the editor's idiosyncracies, which is not ideal.  

So what I've gone ahead and done is made a few changes so that the actual strings used to trigger the symbol are nowhere else referenced in the code.  In particular, if you want to change "exp" to, for example, "exponent" in your `symbols.json` file, you should be able to do entirely free of consequence (`^`, `shift-up`, and `\exponent` will still create exponents exactly as before).  

The plan has always been that different applicatoins would maintain their own `symbols.json` files (kind of like LaTeX .sty files) and the game is how to make that as simple as possible.  It's not ideal right now, but I think this is a step in the right direction.

**Comment by jiggzson** [comment]
I remember solving this problem in a similar manner before but it's been a while so I've sort of forgotten. I think I edited the symbols.json file and removed the entry for exp. It was painless and straightforward. I'll go ahead and do this again but I'll document it somewhere for future versions of the library.

Thanks.
